---

- name: add repo
  apt_repository:
    repo: 'ppa:greenplum/db'
  become: true

- name: install greenplum
  apt:
    name: greenplum-db-6
    update_cache: true
  become: true

- name: find version db
  find:
    path: /opt
    patterns: 'greenplum*'
    file_type: directory
  register: installed_dir
  become: true
  tags:
    - test_install_nginx
    - test_not_install_nginx

- name: create user
  include: configure-user.yml

- name: deploy gpinitsystem
  become: true
  become_user: gpadmin
  become_method: sudo
  shell: "source {{ installed_dir.files[0].path }}/greenplum_path.sh  && gpinitsystem -c /home/gpadmin/gpinitsystem_singlenode -h /home/gpadmin/hostlist_singlenode -a -q --ignore-warnings"
  ignore_errors: true
  changed_when: false
  args:
    executable: /bin/bash

- name: reboot host
  reboot:
  become: true

- name: copy env
  template:
    src: env_systemmd.j2
    dest: /home/{{ greenplum_admin_user }}/env_systemmd
    mode: 0755
    owner: gpadmin
    group: gpadmin
  become: true

- name: Copy config
  template:
    src: greenplum-db.service.j2
    dest: /etc/systemd/system/greenplum-db.service
    owner: gpadmin
    group: gpadmin
    mode: 0744
    force: true
    backup: true
  become: true

- name: reload daemon
  systemd:
    daemon_reload: true
  become: true

- name: enable service
  systemd:
    name: greenplum-db
    enabled: true
    masked: false
    state: started
  become: true

...
